### ISSUE TITLE
firefox issue

### ISSUE THREAD

**Issue by sktniranjan** [godlikemouse/jquery.cube.js#1]
It is working fine in chrome but not working perfectly in firefox 39.0. Is there any solution for this issue?

**Comment by godlikemouse** [comment]
Hi sktniranjan, are you testing this on a native machine or through an emulator?  Being that the WebGL context attempts to use the graphics card for acceleration, if you're not running native you may have problems.  I just tested using Firefox which automatically updated to 44.0.2 and it worked just fine.  I can add a fallback renderer which would be the canvas renderer however, the performance will be very clunky.

**Comment by sktniranjan** [comment]
![rubikcubescreenshot](https://cloud.githubusercontent.com/assets/2901209/13486099/0559a9f0-e134-11e5-807f-b6c75dc50203.PNG)

I have attached my screenshot here. The cube is uncompleted. Tested in firefox 44.0.2. I didn't change anything in code. This is from your site http://codepen.io/godlikemouse/pen/QbGYNX. The same working perfectly in chrome.
It would be great if it is there solution for this.

**Comment by godlikemouse** [comment]
Hi sktniranjan, sorry I mistakenly answered the first question thinking you were using my WebGL version.  This HTML/CSS/JavaScript only version has issues rendering the 3D faces on Firefox and I haven't been able to determine why just yet.  I was hoping that this issue would be fixed in the near future but that doesn't seem to be the case.  I'll have to revisit this in the near future when there is a CSS property that will allow the faces to be displayed correctly (culled) when specified.

**Comment by godlikemouse** [comment]
Hi sktniranjan, I've found a bit of a workaround for the Firefox issue.  The latest has been committed to the github repo.  There may be some slight flickering when the edges animate however, it should be much cleaner and work now.

![screenshot from 2016-03-04 18-25-12](https://cloud.githubusercontent.com/assets/7003154/13545120/7ec43456-e236-11e5-84b4-1adf0d452cd2.png)

**Comment by sktniranjan** [comment]
Thank you godlikemouse. Now Its working fine in firefox. Thank you so much.

**Comment by godlikemouse** [comment]
Sure thing, thanks.
